matrix:
  RUST: [stable, beta, nightly]

steps:
  test:
    image: rust:1-slim
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default $RUST
      - cargo check
  clippy:
    image: rust:1-slim
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup component add clippy
      - cargo clippy
